from HTMLTestRunner import HTMLTestRunner
import time
import unittest

if __name__ == '__main__':
    #测试用例目录
    test_dir = r"C:\Users\Administrator\Desktop\kedalo\Testing\APP\cases"
    #加载测试用例
    discover = unittest.defaultTestLoader.discover(test_dir, pattern="test*.py")
    # 生成测试报告
    now_time = time.strftime("%Y-%m-%d_%H_%M_%S")
    path = r"C:\Users\Administrator\Desktop\kedalo\Testing\APP\report" + now_time + ".html"
    with open(path, 'wb+') as f:
        runner = HTMLTestRunner(stream=f, title='APPInterface Test Report',description='generated by HTMLTestRunner.', verbosity=2)
        # 执行测试集
        runner.run(discover)